/*
=========================================================
E-Commerce Sales Analytics
SQL Business Analysis
Author: Abhineet Verma
=========================================================
*/

-- =====================================================
-- SECTION 1 : BUSINESS KPIs
-- =====================================================

-- Q1. Total Number of Orders

SELECT COUNT(order_id) AS Total_Orders
FROM sales;

----------------------------------------------------------

-- Q2. Total Revenue Generated

SELECT
ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales;

----------------------------------------------------------

-- Q3. Average Revenue Per Order

SELECT
ROUND(AVG(revenue),2) AS Average_Revenue
FROM sales;

----------------------------------------------------------

-- Q4. Total Quantity Sold

SELECT
SUM(quantity) AS Total_Items_Sold
FROM sales;

----------------------------------------------------------

-- Q5. Average Customer Rating

SELECT
ROUND(AVG(customer_rating),2) AS Average_Customer_Rating
FROM sales;

----------------------------------------------------------

-- Q6. Average Delivery Time

SELECT
ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales;

----------------------------------------------------------

-- Q7. Total Number of Customers

SELECT
COUNT(DISTINCT customer_id) AS Total_Customers
FROM sales;

----------------------------------------------------------

-- Q8. Total Discount Given

SELECT
ROUND(SUM(discount),2) AS Total_Discount
FROM sales;


-- =====================================================
-- SECTION 2 : PRODUCT PERFORMANCE ANALYSIS
-- =====================================================

-- Q9. Revenue Generated by Each Product Category

SELECT
    product_category,
    ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales
GROUP BY product_category
ORDER BY Total_Revenue DESC;

----------------------------------------------------------

-- Q10. Quantity Sold by Each Product Category

SELECT
    product_category,
    SUM(quantity) AS Total_Quantity_Sold
FROM sales
GROUP BY product_category
ORDER BY Total_Quantity_Sold DESC;

----------------------------------------------------------

-- Q11. Average Revenue per Category

SELECT
    product_category,
    ROUND(AVG(revenue),2) AS Average_Revenue
FROM sales
GROUP BY product_category
ORDER BY Average_Revenue DESC;

----------------------------------------------------------

-- Q12. Average Customer Rating by Category

SELECT
    product_category,
    ROUND(AVG(customer_rating),2) AS Average_Rating
FROM sales
GROUP BY product_category
ORDER BY Average_Rating DESC;

----------------------------------------------------------

-- Q13. Average Discount Offered by Category

SELECT
    product_category,
    ROUND(AVG(discount),2) AS Average_Discount
FROM sales
GROUP BY product_category
ORDER BY Average_Discount DESC;

----------------------------------------------------------

-- Q14. Highest Revenue Order in Each Category

SELECT
    product_category,
    MAX(revenue) AS Highest_Order_Revenue
FROM sales
GROUP BY product_category
ORDER BY Highest_Order_Revenue DESC;

----------------------------------------------------------

-- Q15. Total Orders by Product Category

SELECT
    product_category,
    COUNT(order_id) AS Total_Orders
FROM sales
GROUP BY product_category
ORDER BY Total_Orders DESC;



-- =====================================================
-- SECTION 3 : REGIONAL SALES ANALYSIS
-- =====================================================

-- Q16. Total Revenue by Region

SELECT
    region,
    ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales
GROUP BY region
ORDER BY Total_Revenue DESC;

----------------------------------------------------------

-- Q17. Total Orders by Region

SELECT
    region,
    COUNT(order_id) AS Total_Orders
FROM sales
GROUP BY region
ORDER BY Total_Orders DESC;

----------------------------------------------------------

-- Q18. Total Quantity Sold by Region

SELECT
    region,
    SUM(quantity) AS Total_Quantity
FROM sales
GROUP BY region
ORDER BY Total_Quantity DESC;

----------------------------------------------------------

-- Q19. Average Revenue per Order by Region

SELECT
    region,
    ROUND(AVG(revenue),2) AS Average_Revenue
FROM sales
GROUP BY region
ORDER BY Average_Revenue DESC;

----------------------------------------------------------

-- Q20. Average Customer Rating by Region

SELECT
    region,
    ROUND(AVG(customer_rating),2) AS Average_Rating
FROM sales
GROUP BY region
ORDER BY Average_Rating DESC;

----------------------------------------------------------

-- Q21. Average Delivery Time by Region

SELECT
    region,
    ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales
GROUP BY region
ORDER BY Average_Delivery_Days;

----------------------------------------------------------

-- Q22. Average Discount by Region

SELECT
    region,
    ROUND(AVG(discount),2) AS Average_Discount
FROM sales
GROUP BY region
ORDER BY Average_Discount DESC;

----------------------------------------------------------

-- Q23. Number of Unique Customers by Region

SELECT
    region,
    COUNT(DISTINCT customer_id) AS Unique_Customers
FROM sales
GROUP BY region
ORDER BY Unique_Customers DESC;



-- =====================================================
-- SECTION 4 : CUSTOMER ANALYSIS
-- =====================================================

-- Q24. Top 10 Customers by Total Revenue

SELECT
    customer_id,
    ROUND(SUM(revenue),2) AS Total_Spent
FROM sales
GROUP BY customer_id
ORDER BY Total_Spent DESC
LIMIT 10;

----------------------------------------------------------

-- Q25. Top 10 Customers by Number of Orders

SELECT
    customer_id,
    COUNT(order_id) AS Total_Orders
FROM sales
GROUP BY customer_id
ORDER BY Total_Orders DESC
LIMIT 10;

----------------------------------------------------------

-- Q26. Average Spending Per Customer

SELECT
    customer_id,
    ROUND(AVG(revenue),2) AS Average_Spending
FROM sales
GROUP BY customer_id
ORDER BY Average_Spending DESC;

----------------------------------------------------------

-- Q27. Total Quantity Purchased by Each Customer

SELECT
    customer_id,
    SUM(quantity) AS Total_Items
FROM sales
GROUP BY customer_id
ORDER BY Total_Items DESC;

----------------------------------------------------------

-- Q28. Highest Single Order by Customer

SELECT
    customer_id,
    MAX(revenue) AS Highest_Order
FROM sales
GROUP BY customer_id
ORDER BY Highest_Order DESC;

----------------------------------------------------------

-- Q29. Customer Rating Given by Customers

SELECT
    customer_id,
    ROUND(AVG(customer_rating),2) AS Average_Rating
FROM sales
GROUP BY customer_id
ORDER BY Average_Rating DESC;

----------------------------------------------------------

-- Q30. Customers Who Have Placed More Than 5 Orders

SELECT
    customer_id,
    COUNT(order_id) AS Total_Orders
FROM sales
GROUP BY customer_id
HAVING COUNT(order_id) > 5
ORDER BY Total_Orders DESC;



-- =====================================================
-- SECTION 5 : PAYMENT METHOD ANALYSIS
-- =====================================================

-- Q31. Number of Orders by Payment Method

SELECT
    payment_method,
    COUNT(order_id) AS Total_Orders
FROM sales
GROUP BY payment_method
ORDER BY Total_Orders DESC;

----------------------------------------------------------

-- Q32. Total Revenue by Payment Method

SELECT
    payment_method,
    ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales
GROUP BY payment_method
ORDER BY Total_Revenue DESC;

----------------------------------------------------------

-- Q33. Average Revenue per Order by Payment Method

SELECT
    payment_method,
    ROUND(AVG(revenue),2) AS Average_Revenue
FROM sales
GROUP BY payment_method
ORDER BY Average_Revenue DESC;

----------------------------------------------------------

-- Q34. Average Customer Rating by Payment Method

SELECT
    payment_method,
    ROUND(AVG(customer_rating),2) AS Average_Rating
FROM sales
GROUP BY payment_method
ORDER BY Average_Rating DESC;

----------------------------------------------------------

-- Q35. Average Delivery Time by Payment Method

SELECT
    payment_method,
    ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales
GROUP BY payment_method
ORDER BY Average_Delivery_Days;

----------------------------------------------------------

-- Q36. Average Discount by Payment Method

SELECT
    payment_method,
    ROUND(AVG(discount),2) AS Average_Discount
FROM sales
GROUP BY payment_method
ORDER BY Average_Discount DESC;



-- =====================================================
-- SECTION 6 : DELIVERY PERFORMANCE ANALYSIS
-- =====================================================

-- Q37. Overall Average Delivery Time

SELECT
    ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales;

----------------------------------------------------------

-- Q38. Average Delivery Time by Region

SELECT
    region,
    ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales
GROUP BY region
ORDER BY Average_Delivery_Days;

----------------------------------------------------------

-- Q39. Average Delivery Time by Product Category

SELECT
    product_category,
    ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales
GROUP BY product_category
ORDER BY Average_Delivery_Days;

----------------------------------------------------------

-- Q40. Average Delivery Time by Payment Method

SELECT
    payment_method,
    ROUND(AVG(delivery_days),2) AS Average_Delivery_Days
FROM sales
GROUP BY payment_method
ORDER BY Average_Delivery_Days;

----------------------------------------------------------

-- Q41. Customer Rating by Delivery Days

SELECT
    delivery_days,
    ROUND(AVG(customer_rating),2) AS Average_Rating,
    COUNT(*) AS Total_Orders
FROM sales
GROUP BY delivery_days
ORDER BY delivery_days;

----------------------------------------------------------

-- Q42. Revenue Generated Based on Delivery Days

SELECT
    delivery_days,
    ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales
GROUP BY delivery_days
ORDER BY delivery_days;

----------------------------------------------------------

-- Q43. Orders Delivered Within 5 Days

SELECT
    COUNT(*) AS Orders_Within_5_Days
FROM sales
WHERE delivery_days <= 5;

----------------------------------------------------------

-- Q44. Orders Delivered After 5 Days

SELECT
    COUNT(*) AS Orders_After_5_Days
FROM sales
WHERE delivery_days > 5;


