-- =====================================================
-- SECTION 2 : PRODUCT PERFORMANCE ANALYSIS
-- =====================================================

-- Q9. Revenue Generated by Each Product Category

SELECT
    product_category,
    ROUND(SUM(revenue),2) AS Total_Revenue
FROM sales
GROUP BY product_category
ORDER BY Total_Revenue DESC;

----------------------------------------------------------

-- Q10. Quantity Sold by Each Product Category

SELECT
    product_category,
    SUM(quantity) AS Total_Quantity_Sold
FROM sales
GROUP BY product_category
ORDER BY Total_Quantity_Sold DESC;

----------------------------------------------------------

-- Q11. Average Revenue per Category

SELECT
    product_category,
    ROUND(AVG(revenue),2) AS Average_Revenue
FROM sales
GROUP BY product_category
ORDER BY Average_Revenue DESC;

----------------------------------------------------------

-- Q12. Average Customer Rating by Category

SELECT
    product_category,
    ROUND(AVG(customer_rating),2) AS Average_Rating
FROM sales
GROUP BY product_category
ORDER BY Average_Rating DESC;

----------------------------------------------------------

-- Q13. Average Discount Offered by Category

SELECT
    product_category,
    ROUND(AVG(discount),2) AS Average_Discount
FROM sales
GROUP BY product_category
ORDER BY Average_Discount DESC;

----------------------------------------------------------

-- Q14. Highest Revenue Order in Each Category

SELECT
    product_category,
    MAX(revenue) AS Highest_Order_Revenue
FROM sales
GROUP BY product_category
ORDER BY Highest_Order_Revenue DESC;

----------------------------------------------------------

-- Q15. Total Orders by Product Category

SELECT
    product_category,
    COUNT(order_id) AS Total_Orders
FROM sales
GROUP BY product_category
ORDER BY Total_Orders DESC;